CREATE TABLE ROLES(
ROLE_ID INT NOT NULL,
ROLE_NAME VARCHAR(20) NOT NULL,
PRIMARY KEY(ROLE_ID)
)

CREATE TABLE USERDATA(
UNAME VARCHAR(20) NOT NULL,
PWD VARCHAR(20) NOT NULL,
ROLE_ID INT NOT NULL,
EMPID VARCHAR(10),
PRIMARY KEY (USERNAME),
FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ROLE_ID)
)